server:
    port: 8084
spring:
    application:
        eureka:
            client:
                fetch-registry: true
                register-with-eureka: true
                service-url:
                    defaultZone: http://localhost:8761/eureka
        name: API-GATEWAY
    cloud:
        gateway:
            routes:
            -   id: USER-SERVICE
                uri: http://localhost:8081
                predicates:
                - Path=/user/**

            - id: HOTEL-SERVICE
              uri: http://localhost:8082
              predicates:
                  - Path=/hotel/**

            - id: USER-SERVICE
              uri: http://localhost:8083
              predicates:
                  - Path=/rating/**

